apiVersion: batch/v1
kind: Job
metadata:
  name: check-storageclass
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pre-install-check-storageclass
        image: mcr.microsoft.com/oss/kubernetes/kubectl:v1.25.10
        command:
        - /bin/bash
        - -c
        - |
          if ! kubectl get storageclass {{ .Values.storageClassName }} > /dev/null 2>&1; then
            echo "Error: Storage class {{ .Values.storageClassName }} not found"
            exit 1
          fi
      restartPolicy: Never